"""
Development seed script for ArogyaPlus Healthcare.

Usage (from backend/app/):
    python -m app.seed.seed_data

Creates the single admin account (from environment variables) and the
parameter catalog imported from the lab's parameter sheet. Safe to run
multiple times - existing records are left untouched.
"""

from app.core.config import settings
from app.core.security import hash_password
from app.db.base import Base  # noqa: F401  (imports all models for metadata.create_all)
from app.db.session import SessionLocal, engine
from app.models.admin import Admin
from app.models.parameter import Parameter

# Column order for each row in PARAMETERS_DATA.
PARAMETER_FIELDS = (
    "name",
    "method",
    "description",
)

# Imported from the lab's test/parameter sheet (Book_AllTests.xlsx).
PARAMETERS_DATA = [
    ('ADRENOCORTICOTROPIC HORMONE TEST', 'C.L.I.A', 'Regulate stress response, blood pressure, and fluid balance.'),
    ('ALANINE TRANSAMINASE (SGPT)', 'Photometry', 'Assess how well the liver synthesizes proteins and processes waste.'),
    ('ALBUMIN - SERUM', 'Photometry', 'Assess how well the liver synthesizes proteins and processes waste.'),
    ('ALDOSTERONE', 'C.L.I.A', 'Regulate stress response, blood pressure, and fluid balance.'),
    ('ALKALINE PHOSPHATASE', 'Photometry', 'Assess how well the liver synthesizes proteins and processes waste.'),
    ('ALPHA FETO PROTEIN (AFP)', 'C.L.I.A', 'Screening for specific cellular changes or oncological risks.'),
    ('AMYLASE', 'Photometry', 'Check for pancreatic inflammation'),
    ('ANTI NUCLEAR ANTIBODIES (ANA)', 'C.L.I.A', 'Identify systemic inflammation and autoimmune activity.'),
    ('ANDROSTENEDIONE', 'C.L.I.A', 'Evaluate endocrine disorders or find source of suspected hormonal imbalance'),
    ('ANTI - CCP (ACCP)', 'C.L.I.A', 'Address joint inflammation or clarify autoimmune status'),
    ('ANTI – SYPHILIS ANTIBODY', 'C.L.I.A', 'To screen and diagnose infection with Treponema pallidum'),
    ('ANTI HEPATITIS A VIRUS (HAV) - IGM', 'C.L.I.A', 'Looks for Immunoglobulin M (IgM) antibodies, very first defense proteins the body creates during a new infection'),
    ('ANTI HEPATITIS A VIRUS (HAV) - TOTAL', 'C.L.I.A', 'Measures both IgM (active defense) and IgG (long-term memory) antibodies combined'),
    ('ANTI HEPATITIS B CORE ANTIGEN (AHBC) - IGM', 'C.L.I.A', 'Detects short-term core antibodies, indicator of a new, acute Hepatitis B infection'),
    ('ANTI HEPATITIS B CORE ANTIGEN (AHBC) - TOTAL', 'C.L.I.A', 'Measures the combined total of IgM and IgG core antibodies'),
    ('ANTI HEPATITIS C VIRUS ANTIBODY', 'C.L.I.A', 'Screens for antibodies against the Hepatitis C virus.'),
    ('ANTI MICROSOMAL ANTIBODY (AMA)', 'C.L.I.A', None),
    ('ANTI MULLERIAN HORMONE (AMH)', 'C.L.I.A', None),
    ('ANTI THYROGLOBULIN ANTIBODY (ATG)', 'C.L.I.A', 'Measures the level of specific autoantibodies that mistakenly target and attack thyroglobuli'),
    ('ANTI-CARDIOLIPIN IGG', 'C.L.I.A', 'Thyroid Hormone'),
    ('ANTI-CARDIOLIPIN IGM', 'C.L.I.A', None),
    ('ANTI-DENGUE VIRUS IGG', 'C.L.I.A', None),
    ('ANTI-DENGUE VIRUS IGM', 'C.L.I.A', None),
    ('ANTI-DSDNA IGG', 'C.L.I.A', None),
    ('APOLIPOPROTEIN - A1 (APO-A1)', 'Photometry', 'Measures the specific protein that forms the structural backbone of High-Density Lipoprotein (HDL)—commonly known as "good" cholesterol'),
    ('APOLIPOPROTEIN - B (APO-B)', 'Photometry', 'Measures the total amount of a specific protein found on the surface of all potentially harmful, plaque-causing cholesterol particles.'),
    ('ASPARTATE AMINOTRANSFERASE (SGOT)', 'Photometry', 'Measure specific proteins, enzymes, and waste products in your blood to evaluate how well your liver is synthesizing vital molecules, filtering toxins, and processing digestive bile'),
    ('BETA HCG', 'C.L.I.A', 'Pregnancy Monitoring, confirms and tracks early pregnancy progress.'),
    ('BILIRUBIN - DIRECT', 'Photometry', 'Measure specific proteins, enzymes, and waste products in your blood to evaluate how well your liver is synthesizing vital molecules, filtering toxins, and processing digestive bile'),
    ('BILIRUBIN - TOTAL', 'Photometry', 'Measure specific proteins, enzymes, and waste products in your blood to evaluate how well your liver is synthesizing vital molecules, filtering toxins, and processing digestive bile'),
    ('BLOOD UREA NITROGEN (BUN)', 'Photometry', 'Evaluate how effectively your kidneys filter metabolic waste products, maintain proper fluid balances, and regulate essential body minerals.'),
    ('CA125', 'C.L.I.A', 'Cancer Antigen - specialized protein marker to investigate pelvic masses, monitor specific high-risk scenarios, treatment timelines.'),
    ('CA15-3', 'C.L.I.A', 'Cancer Antigen, a protein primarily associated with breast tissue'),
    ('CA19-9', 'C.L.I.A', 'Cancer Antigen, a protein most heavily linked to the gastrointestinal system, especially the pancreas'),
    ('CALCITONIN', 'C.L.I.A', None),
    ('CALCIUM', 'Photometry', 'Evaluate how effectively your kidneys filter metabolic waste products, maintain proper fluid balances, and regulate essential body minerals.'),
    ('CARCINO EMBRYONIC ANTIGEN (CEA)', 'C.L.I.A', 'Cancer Screening, measures the level of a specific glycoprotein in the body'),
    ('CHLAMYDIA PNEUMONIAE IGM', 'C.L.I.A', None),
    ('COMPLETE URINE ANALYSIS', 'Microscopy', 'Search for urinary tract infections, kidney issues, or metabolic problems.'),
    ('CORTISOL', 'C.L.I.A', "Stress hormone, plays vital role regulating body's fight response, blood pressure, blood sugar levels, metabolism, and immune system"),
    ('C-PEPTIDE', 'C.L.I.A', 'Evaluate glucose metabolism and insulin production'),
    ('C-REACTIVE PROTEIN (CRP)', 'Photometry', 'Provide deeper insight into arterial inflammation and plaque risk'),
    ('CREATINE PHOSPHOKINASE', 'Photometry', 'Evaluate generalized muscle or tissue breakdown'),
    ('CREATININE - SERUM', 'Photometry', 'Evaluate how effectively your kidneys filter metabolic waste products, maintain proper fluid balances, and regulate essential body minerals.'),
    ('CREATININE PHOSPHOKINASE (MUSCLE/BRAIN)', 'C.L.I.A', 'To evaluate acute chest pain or investigate suspected muscular issues:'),
    ('CYTOMEGALO VIRUS (CMV) IGG', 'C.L.I.A', None),
    ('CYTOMEGALO VIRUS (CMV) IGM', 'C.L.I.A', None),
    ('DENGUE VIRUS NS1 ANTIGEN', 'C.L.I.A', None),
    ('DHEA - SULPHATE (DHEAS)', 'C.L.I.A', 'To investigate reproductive issues, androgen excess, or gland disorders:'),
    ('DIRECT RENIN', 'C.L.I.A', None),
    ('SERUM ELECTROLYTES', 'I.M.T', 'To check your hydration or screen for sudden cellular stress'),
    ('ESTRADIOL/OESTROGEN (E2)', 'C.L.I.A', 'To investigate reproductive timelines, fertility concerns, or developmental changes'),
    ('FASTING BLOOD SUGAR', 'Photometry', 'Evaluate glucose metabolism and insulin production'),
    ('FERRITIN', 'C.L.I.A', 'Monitor iron deficiencies in our body'),
    ('FOLATE', 'C.L.I.A', 'Vitamin test to investigate unexplained changes in your blood cells or to ensure optimal health during specific life stages'),
    ('FOLLICLE STIMULATING HORMONE (FSH)', 'C.L.I.A', 'Hormone test to investigate fertility, menstrual irregularities, Infertility & Ovulation, Confirming Menopause & Evaluating Puberty Timelines'),
    ('FREE PSA', 'C.L.I.A', 'Screening for specific cellular changes or oncological risks.'),
    ('FREE THYROXINE (FT4)', 'C.L.I.A', 'Evaluate the physical function and regulatory feedback loop of your thyroid gland'),
    ('FREE TRIIODOTHYRONINE (FT3)', 'C.L.I.A', 'Evaluate the physical function and regulatory feedback loop of your thyroid gland'),
    ('FREE TESTOSTERONE', 'C.L.I.A', 'Measures the remaining 1% to 2% of the hormone that is completely unattached to any blood proteins'),
    ('GAMMA GLUTAMYL TRANSFERASE (GGT)', 'Photometry', 'Measure specific proteins, enzymes, and waste products in your blood to evaluate how well your liver is synthesizing vital molecules, filtering toxins, and processing digestive bile'),
    ('HUMAN GROWTH HORMONE', 'C.L.I.A', 'Hormones'),
    ('H.PYLORI IGG', 'C.L.I.A', 'To investigate chronic digestive discomfort and pinpoint the root cause of upper gastrointestinal issues'),
    ('HBA1C', 'H.P.L.C', 'Foundational test to identify blood sugar issues and track long-term metabolic health'),
    ('HDL CHOLESTEROL - DIRECT', 'Photometry', 'Measures the specific fats and fatty substances (lipids) circulating in your bloodstream'),
    ('HEMOGRAM - 6 PART (DIFF)', 'Hematology', 'CBC BLA BLA'),
    ('HEPATITIS B ENVELOPE ANTIBODY - AHBE', 'C.L.I.A', None),
    ('HEPATITIS B ENVELOPE ANTIGEN (HBEAG)', 'C.L.I.A', None),
    ('HEPATITIS B SURFACE ANTIBODY (ANTI-HBS)', 'C.L.I.A', 'Viral Infection'),
    ('HEPATITIS B SURFACE ANTIGEN', 'C.L.I.A', 'Evaluate exposure, active liver stress, or safety during Active Infection, Routine Prenatal Screening, mandatory for all pregnant individuals.'),
    ('HERPES SIMPLEX VIRUS 1/2 - IGG', 'C.L.I.A', 'Viral Infection'),
    ('HERPES SIMPLEX VIRUS 1/2 - IGM', 'C.L.I.A', None),
    ('HERPES SIMPLEX VIRUS I - IGG', 'C.L.I.A', None),
    ('HERPES SIMPLEX VIRUS I - IGM', 'C.L.I.A', None),
    ('HERPES SIMPLEX VIRUS II - IGG', 'C.L.I.A', None),
    ('HERPES SIMPLEX VIRUS II - IGM', 'C.L.I.A', None),
    ('HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)', 'Photometry', 'Provide deeper insight into arterial inflammation and plaque risk'),
    ('HIGH SENSITIVITY TROPONIN I', 'C.L.I.A', 'Detects heart muscle damage, while NT-proBNP checks for heart strain or failure.'),
    ('HIV P24 AG/AB', 'C.L.I.A', 'Viral Infection'),
    ('HOMOCYSTEINE', 'C.L.I.A', 'Provide deeper insight into arterial inflammation and plaque risk'),
    ('INSULIN - FASTING', 'C.L.I.A', 'Evaluate glucose metabolism and insulin production'),
    ('INSULIN - PP', 'C.L.I.A', 'Diabetes'),
    ('INTACT PARATHYROID HORMONE (PTH)', 'C.L.I.A', 'Kidney & Calcium'),
    ('IRON', 'Photometry', 'Monitor iron deficiencies in our body'),
    ('LACTATE DEHYDROGENASE', 'Photometry', None),
    ('LDL CHOLESTEROL - DIRECT', 'Photometry', 'Measures the specific fats and fatty substances (lipids) circulating in your bloodstream'),
    ('LIPASE', 'Photometry', 'Check for pancreatic inflammation'),
    ('LIPOPROTEIN (A)', 'Photometry', 'Advanced, highly specific cardiovascular blood tests used to uncover genetic and hidden risks for heart attacks and strokes'),
    ('LIPOPROTEIN ASSOCIATED PHOSPHOLIPASE A2 (LP-PLA2)', 'C.L.I.A', 'Advanced, highly specific cardiovascular blood tests used to uncover genetic and hidden risks for heart attacks and strokes'),
    ('LUTEINISING HORMONE (LH)', 'C.L.I.A', 'To evaluate reproductive health, trace the origin of a hormonal imbalance, or map out fertility timelines'),
    ('MAGNESIUM', 'Photometry', 'Track essential electrolyte and bone minerals'),
    ('NT-PROBNP', 'C.L.I.A', None),
    ('PERIPHERAL BLOOD SMEAR (PBS)', 'Microscopy', 'Look directly red blood cells, white blood cells, and platelets for evaluating Chronic Fatigue and Weakness'),
    ('PHOSPHOROUS', 'Photometry', 'Track essential electrolyte and bone minerals'),
    ('POSTPRANDIAL BLOOD SUGAR', 'Photometry', None),
    ('PROGESTERONE', 'C.L.I.A', 'To investigate reproductive timelines, fertility concerns, or early pregnancy complications'),
    ('PROLACTIN (PRL)', 'C.L.I.A', 'To investigate reproductive system disruptions, menstrual irregularities, or suspected pituitary gland issues'),
    ('PROSTATE SPECIFIC ANTIGEN (PSA)', 'C.L.I.A', 'Screening for specific cellular changes or oncological risks.'),
    ('PROTEIN - TOTAL', 'Photometry', 'Measure specific proteins, enzymes, and waste products in your blood to evaluate how well your liver is synthesizing vital molecules, filtering toxins, and processing digestive bile'),
    ('RANDOM BLOOD SUGAR', 'Photometry', None),
    ('RHEUMATOID FACTOR (RF)', 'Photometry', 'Investigating persistent joint issues or evaluating complex autoimmune profiles like Arthritis'),
    ('RUBELLA - IGG', 'C.L.I.A', 'Viral Infection'),
    ('RUBELLA IGM', 'C.L.I.A', 'Viral Infection'),
    ('SERUM COPPER', 'Photometry', 'Track essential electrolyte and bone minerals'),
    ('SERUM ZINC', 'Photometry', 'Track essential electrolyte and bone minerals'),
    ('SEX HORMONE BINDING GLOBULIN', 'C.L.I.A', 'Measures the level of a specific protein produced primarily by your liver'),
    ('TESTOSTERONE', 'C.L.I.A', 'Measures the aggregate sum of all testosterone in your bloodstream'),
    ('THYROGLOBULIN', 'C.L.I.A', None),
    ('THYROID STIMULATING HORMONE (TSH)', 'C.L.I.A', 'Look for autoimmune thyroid diseases'),
    ('TOTAL CHOLESTEROL', 'Photometry', 'Measures the specific fats and fatty substances (lipids) circulating in your bloodstream'),
    ('TOTAL IGE', 'C.L.I.A', 'Allergic'),
    ('TOTAL IRON BINDING CAPACITY (TIBC)', 'Photometry', 'Monitor iron deficiencies in our body'),
    ('TOTAL THYROXINE (T4)', 'C.L.I.A', 'Evaluate the physical function and regulatory feedback loop of your thyroid gland'),
    ('TOTAL TRIIODOTHYRONINE (T3)', 'C.L.I.A', 'Evaluate the physical function and regulatory feedback loop of your thyroid gland'),
    ('TOXOPLASMA GONDII IGG', 'C.L.I.A', None),
    ('TOXOPLASMA GONDII IGM', 'C.L.I.A', None),
    ('TRIGLYCERIDES', 'Photometry', 'Measures the specific fats and fatty substances (lipids) circulating in your bloodstream'),
    ('URIC ACID', 'Photometry', 'Evaluate how effectively your kidneys filter metabolic waste products, maintain proper fluid balances, and regulate essential body minerals.'),
    ('URINARY MICROALBUMIN', 'Photometry', 'Detects early kidney damage by checking for protein leaks in urine.'),
    ('URINOGRAM', 'Microscopy', None),
    ('VITAMIN B-12', 'C.L.I.A', 'Vitamin test to investigate unexplained changes in your blood cells or to ensure optimal health during specific life stages'),
    ('17-OH PROGESTERONE', 'C.L.I.A', None),
    ('25-OH VITAMIN D (TOTAL)', 'C.L.I.A', 'Vitamin test to investigate unexplained changes in your blood cells or to ensure optimal health during specific life stages'),
    ('SERUM GLOBULIN', None, 'Measure specific proteins, enzymes, and waste products in your blood to evaluate how well your liver is synthesizing vital molecules, filtering toxins, and processing digestive bile'),
    ('SODIUM', None, None),
    ('POTASSIUM', None, None),
    ('CHLORIDE', None, None),
    ('EST. GLOMERULAR FILTRATION RATE (EGFR)', None, None),
    ('BUN / SR.CREATININE RATIO', None, None),
    ('AVERAGE BLOOD GLUCOSE (ABG)', None, None),
    ('TOTAL LEUCOCYTES COUNT (WBC)', None, None),
    ('HEMOGLOBIN', None, None),
    ('PLATELET COUNT', None, None),
    ('TOTAL RBC', None, None),
    ('HEMATOCRIT(PCV)', None, None),
    ('MEAN CORPUSCULAR VOLUME(MCV)', None, None),
    ('MEAN CORPUSCULAR HEMOGLOBIN(MCH)', None, None),
    ('MEAN CORP.HEMO.CONC(MCHC)', None, None),
    ('RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)', None, None),
    ('RED CELL DISTRIBUTION WIDTH (RDW-CV)', None, None),
    ('NEUTROPHILS', None, None),
    ('LYMPHOCYTE PERCENTAGE', None, None),
    ('MONOCYTES', None, None),
    ('EOSINOPHILS', None, None),
    ('BASOPHILS', None, None),
    ('NEUTROPHILS - ABSOLUTE COUNT', None, None),
    ('LYMPHOCYTES - ABSOLUTE COUNT', None, None),
    ('MONOCYTES - ABSOLUTE COUNT', None, None),
    ('EOSINOPHILS - ABSOLUTE COUNT', None, None),
    ('BASOPHILS - ABSOLUTE COUNT', None, None),
    ('MEAN PLATELET VOLUME(MPV)', None, None),
    ('VLDL CHOLESTEROL', None, None),
    ('NON-HDL CHOLESTEROL', None, None),
    ('TC/ HDL CHOLESTEROL RATIO', None, None),
    ('LDL / HDL RATIO', None, None),
    ('BILIRUBIN (INDIRECT)', None, None),
    ('SERUM ALB/GLOBULIN RATIO', None, None),
    ('% TRANSFERRIN SATURATION', None, None),
    ('APO B / APO A1 RATIO (APO B/A1)', None, None),
    ('WHITE BLOOD CELLS', None, None),
    ('NON SQUAMOUS EPITHELIA', None, None),
    ('WHITE BLOOD CELLS CLUMPS', None, None),
    ('TRIPLE PHOSPHATE CRYSTALS', None, None),
    ('BACTERIA COCA', None, None),
    ('MUCUS', None, None),
    ('RED BLOOD CELLS', None, None),
    ('URIC ACID CRYSTALS', None, None),
    ('HYALINE CYLINDERS', None, None),
    ('YEAST', None, None),
    ('SQUAMOUS EPITHELIA', None, None),
    ('CALCIUM OXALATE', None, None),
    ('BACTERIA RODS', None, None),
    ('PATHOLOGICAL CYLINDRES (CAST)', None, None),
    ('URINE KETONE', None, None),
    ('URINARY BILIRUBIN', None, None),
    ('UROBILINOGEN', None, None),
    ('SPECIFIC GRAVITY', None, None),
    ('LEUCOCYTE ESTERASE', None, None),
    ('URINE BLOOD', None, None),
    ('URINARY PROTEIN', None, None),
    ('COLOUR', None, None),
    ('NITRITE', None, None),
    ('PH', None, None),
    ('APPEARANCE', None, None),
    ('URINARY GLUCOSE', None, None),
    ('CREATININE - URINE', None, None),
    ('URI. ALBUMIN/CREATININE RATIO (UA/C)', None, None),
    ('ERYTHROCYTE SEDIMENTATION RATE (ESR)', None, None),
    ('HOMA INSULIN RESISTANCE INDEX', None, None),
    ('RH TYPING', None, None),
    ('BLOOD GROUPING', None, None),
    ('PERCENT FREE PSA', None, None),
    ('TREPONEMA PALLIDUM HAEMAGGLUTINATION (TPHA)', None, None),
    ('HELICOBACTER PYLORI - IGG', None, None),
    ('ALPHA2 MACROGLOBULIN', None, None),
    ('ALPHA-1-ANTITRYPSIN (AAT)', None, None),
    ('CARDIOLIPIN ANTIBODY (ACL) - IGA', None, None),
    ('ACID PHOSPHATASE', None, None),
    ('ACETYLCHOLINE RECEPTOR AUTOANTIBODY', None, None),
    ('ADENOSINE DEAMINASE', None, None),
    ('ANTIDNASE-B (DNB)', None, None),
    ('ALLERGY ALPHA LACTOGLOBULIN (BY ELISA)', None, None),
    ('ALLERGY DRUG AMOXYCILLIN (BY ELISA)', None, None),
    ('ALLERGY DRUG ASPIRIN (BY ELISA)', None, None),
    ('ALLERGY BAJRA (BY ELISA)', None, None),
    ('ALLERGY BARLEY (BY ELISA)', None, None),
    ('ALLERGY BETA LACTOGLOBULIN (BY ELISA)', None, None),
    ('ALLERGY BRINJAL (BY ELISA)', None, None),
    ('ALLERGY DRUG BROMHEXINE (BY ELISA)', None, None),
    ('ALLERGY DRUG BRUFEN (IBUPROFEN) (BY ELISA)', None, None),
    ('ALLERGY BUFFALO DANDER (BY ELISA)', None, None),
    ('ALLERGY CAPSICUM (BY ELISA)', None, None),
    ('ALLERGY CARDAMOM (BY ELISA)', None, None),
    ('ALLERGY CASEIN (BY ELISA)', None, None),
    ('ALLERGY CAULIFLOWER (BY ELISA)', None, None),
    ('ALLERGY COCOA (BY ELISA)', None, None),
    ('ALLERGY DRUG CEFIXIME (CEFACLOR) (BY ELISA)', None, None),
    ('ALLERGY CHICKEN DROPPING (BY ELISA)', None, None),
    ('ALLERGY CHERRY (BY ELISA)', None, None),
    ('ALLERGY CHICKEN FEATHERS (BY ELISA)', None, None),
    ('ALLERGY CHOCOLATE (BY ELISA)', None, None),
    ('ALLERGY CHILI PEPPER (BY ELISA)', None, None),
    ('ALLERGY CHEESE (BY ELISA)', None, None),
    ('ALLERGY DRUG CIPROFLOXACIN (BY ELISA)', None, None),
    ('ALLERGY DRUG CLOXACILLIN (BY ELISA)', None, None),
    ('ALLERGY CLOVES (BY ELISA)', None, None),
    ('ALLERGY COCKROACH DUST (BY ELISA)', None, None),
    ('ALLERGY COTTON LINTERS (BY ELISA)', None, None),
    ('ALLERGY CRAB (BY ELISA)', None, None),
    ('ALLERGY CURRY (BY ELISA)', None, None),
    ('ALLERGY CUMIN (BY ELISA)', None, None),
    ('ALLERGY CURD (BY ELISA)', None, None),
    ('ALLERGY DAL CHANA (BY ELISA)', None, None),
    ('ALLERGY DETERGENT (BY ELISA)', None, None),
    ('ALLERGY DRUG DICLOFENAC (BY ELISA)', None, None),
    ('ALLERGY DRUG DOXYCYCLINE (BY ELISA)', None, None),
    ('ALLERGY EGG PLANT/AUBERGINE (BY ELISA)', None, None),
    ('ALLERGY DRUG ERYTHROMYCIN (BY ELISA)', None, None),
    ('ALLERGY FENNEL SEED (BY ELISA)', None, None),
    ('ALLERGY FIG (BY ELISA)', None, None),
    ('ALLERGY GINGER (BY ELISA)', None, None),
    ('ALLERGY GOAT DANDER (BY ELISA)', None, None),
    ('ALLERGY GRAPE (BY ELISA)', None, None),
    ('ALLERGY GUAVA (BY ELISA)', None, None),
    ('ALLERGY HAIR DYE (BY ELISA)', None, None),
    ('ALLERGY HAY DUST (BY ELISA)', None, None),
    ('ALLERGY HOUSE DUST (BY ELISA)', None, None),
    ('ALLERGY HOUSE FLY (BY ELISA)', None, None),
    ('ALLERGY HONEY (BY ELISA)', None, None),
    ('ALLERGY JOWAR (BY ELISA)', None, None),
    ('ALLERGY KIWI (BY ELISA)', None, None),
    ('ALLERGY MANGO (BY ELISA)', None, None),
    ('ALLERGY MASOOR DAL (BY ELISA)', None, None),
    ('ALLERGY MELON (BY ELISA)', None, None),
    ('ALLERGY DRUG METAMIZOL (BY ELISA)', None, None),
    ('ALLERGY MILLET (BY ELISA)', None, None),
    ('ALLERGY MOONG DAL (BY ELISA)', None, None),
    ('ALLERGY MOSQUITO (BY ELISA)', None, None),
    ('ALLERGY MUSHROOM (BY ELISA)', None, None),
    ('ALLERGY MUSTARD (BY ELISA)', None, None),
    ('ALLERGY MUTTON (BY ELISA)', None, None),
    ('ALLERGY DRUG NORFLOXACIN (BY ELISA)', None, None),
    ('ALLERGY DRUG OFLOXACIN (BY ELISA)', None, None),
    ('ALLERGY DRUG OXACILLIN (BY ELISA)', None, None),
    ('ALLERGY PAINTS (BY ELISA)', None, None),
    ('ALLERGY DRUG PARACETAMOL (BY ELISA)', None, None),
    ('ALLERGY PAPER DUST (BY ELISA)', None, None),
    ('ALLERGY PEAS (BY ELISA)', None, None),
    ('ALLERGY DRUG PENICILLIN (BY ELISA)', None, None),
    ('ALLERGY TIMOTHY GRASS (BY ELISA)', None, None),
    ('ALLERGY PIGEON DROPPING (BY ELISA)', None, None),
    ('ALLERGY PISTACHIO NUT (BY ELISA)', None, None),
    ('ALLERGY PLUM (BY ELISA)', None, None),
    ('ALLERGY POMEGRANATE (BY ELISA)', None, None),
    ('ALLERGY PRAWN (BY ELISA)', None, None),
    ('ALLERGY PERFUME (BY ELISA)', None, None),
    ('ALLERGY PARTHENIUM (COMMON RAGWEED) (BY ELISA)', None, None),
    ('ALLERGY PUMPKIN SEED (BY ELISA)', None, None),
    ('ALLERGY RAGI (BY ELISA)', None, None),
    ('ALLERGY RAISIN (BY ELISA)', None, None),
    ('ALLERGY RAJMA DAL (BY ELISA)', None, None),
    ('ALLERGY SAFFRON (BY ELISA)', None, None),
    ('ALLERGY SEMOLINA(RAWA) (BY ELISA)', None, None),
    ('ALLERGY STORAGE MITE (BY ELISA)', None, None),
    ('ALLERGY DRUG SULPHA (BY ELISA)', None, None),
    ('ALLERGY SUNFLOWER (BY ELISA)', None, None),
    ('ALLERGY SWEET POTATO (BY ELISA)', None, None),
    ('ALLERGY DRUG TETRACYCLINE (BY ELISA)', None, None),
    ('ALLERGY DRUG TINIDAZOLE (BY ELISA)', None, None),
    ('ALLERGY TOBBACO (BY ELISA)', None, None),
    ('ALLERGY TOOR DAL (BY ELISA)', None, None),
    ('ALLERGY TURMERIC (BY ELISA)', None, None),
    ('ALLERGY UDAD DAL (BY ELISA)', None, None),
    ('ALLERGY WATERMELON (BY ELISA)', None, None),
    ('ALLERGY WOOD DUST (BY ELISA)', None, None),
    ('ALLERGY DRUG XYLOCAINE (LIDOCAINE) (BY ELISA)', None, None),
    ('ALLERGY YOGURT (BY ELISA)', None, None),
    ('ASPERGILLUS GALACTOMANNAN ANTIGEN', None, None),
    ('ADULT HEMOGLOBIN ELECTROPHORESIS', None, None),
    ('1.5 ANHYDROGLUCITOL', None, None),
    ('ALDOLASE', None, None),
    ('ALPHA HYDROXYBUTYRATE DEHYDROGENASE', None, None),
    ('ANTINUCLEAR ANTIBODIES-17 BLOT', None, None),
    ('ANGIOTENSIN CONVERTING ENZYME', None, None),
    ('ALLERGY ALMOND (BY PHADIA)', None, None),
    ('ALLERGY ALTERNARIA ALTERNATA (BY PHADIA)', None, None),
    ('ALLERGY APPLE (BY PHADIA)', None, None),
    ('ALLERGY ASPERGILLUS FUMIGATUS (BY PHADIA)', None, None),
    ('ALLERGY ASPERGILLUS NIGER (BY PHADIA)', None, None),
    ('ALLERGY ASPERGILLUS FLAVUS (BY PHADIA)', None, None),
    ('ALLERGY ASPERGILLUS TERREUS (BY PHADIA)', None, None),
    ('ALLERGY ASTHMA / RHINITIS SCREENING (BY PHADIA)', None, None),
    ('ALLERGY BAHIA GRASS (BY PHADIA)', None, None),
    ('ALLERGY BANANA (BY PHADIA)', None, None),
    ('ALLERGY BEEF (BY PHADIA)', None, None),
    ('ALLERGY BERMUDA GRASS (BY PHADIA)', None, None),
    ('ALLERGY BLUE MUSSEL (BY PHADIA)', None, None),
    ('ALLERGY BRAZIL NUT (BY PHADIA)', None, None),
    ('ALLERGY CABBAGE (PHADIA)', None, None),
    ('ALLERGY CANDIDA ALBICANS (BY PHADIA)', None, None),
    ('ALLERGY CARROT (BY PHADIA)', None, None),
    ('ALLERGY CASHEW NUT (BY PHADIA)', None, None),
    ('ALLERGY CAT DANDER (BY PHADIA)', None, None),
    ('ALLERGY CELERY (BY PHADIA)', None, None),
    ('ALLERGY CEREAL/VEG FOOD PANEL (BY PHADIA)', None, None),
    ('ALLERGY CHICKEN (BY PHADIA)', None, None),
    ('ALLERGY CHICK PEA (BY PHADIA)', None, None),
    ('ALLERGY CLADOSPORIUM HERBARUM (BY PHADIA)', None, None),
    ('ALLERGY COMMON SILVER BIRCH (BY PHADIA)', None, None),
    ('ALLERGY COCKROACH GERMAN (BY PHADIA)', None, None),
    ('ALLERGY COMPREHENSIVE PROFILE (BY PHADIA)', None, None),
    ('ALLERGY COCONUT (BY PHADIA)', None, None),
    ('ALLERGY COW DANDER (BY PHADIA)', None, None),
    ('ALLERGY COMMON PIGWEED (BY PHADIA)', None, None),
    ('ALLERGY CUCUMBER (BY PHADIA)', None, None),
    ('ALLERGY CULTIVATED RYE (BY PHADIA)', None, None),
    ('ALLERGY DOG DANDER (BY PHADIA)', None, None),
    ('ALLERGY HOUSE DUST (BY PHADIA)', None, None),
    ('ALLERGY DUST PANEL (BY PHADIA)', None, None),
    ('ALLERGY PEACH (BY PHADIA)', None, None),
    ('ALLERGY ECZEMA SCREENING PANEL (BY PHADIA)', None, None),
    ('ALLERGY EGG (BY PHADIA)', None, None),
    ('ALLERGY EGG WHITE (BY PHADIA)', None, None),
    ('ALLERGY ELM (BY PHADIA)', None, None),
    ('ALLERGY PENICILLIUM CHRYSOGENUM (BY PHADIA)', None, None),
    ('ALLERGY FISH COD (BY PHADIA)', None, None),
    ('ALLERGY FOOD PANEL 1 (BY PHADIA)', None, None),
    ('ALLERGY FRUIT PANEL 1 (BY PHADIA)', None, None),
    ('ALLERGY FRUIT PANEL 2 (BY PHADIA)', None, None),
    ('ALLERGY GARLIC (BY PHADIA)', None, None),
    ('ALLERGY GLUTEN (BY PHADIA)', None, None),
    ('ALLERGY ANIMAL PANEL (BY PHADIA)', None, None),
    ('ALLERGY HAZEL NUT (BY PHADIA)', None, None),
    ('ALLERGY HOUSE DUST MITE- D.FARINAE (BY PHADIA)', None, None),
    ('ALLERGY HOUSE DUST MITE - D.PTERONYSSINUS (BY PHADIA)', None, None),
    ('ALLERGY HORSE DANDER (BY PHADIA)', None, None),
    ('ALLERGY INSULIN HUMAN (BY PHADIA)', None, None),
    ('ALLERGY JOHNSON GRASS (BY PHADIA)', None, None),
    ('ALLERGY LEMON (BY PHADIA)', None, None),
    ('ALLERGY LENTIL (BY PHADIA)', None, None),
    ('ANTI PHOSPHOLIPID IGG', None, None),
    ('ANTI PHOSPHOLIPID ANTIBODY (APL) - IGM', None, None),
    ('ALLERGY LOBSTER (BY PHADIA)', None, None),
    ('ALLERGY MAIZE (BY PHADIA)', None, None),
    ('ALLERGY MEADOW GRASS (BY PHADIA)', None, None),
    ('ALLERGY MESQUITE (BY PHADIA)', None, None),
    ('ALLERGY MILK (BY PHADIA)', None, None),
    ('ALLERGY MUCOR RACEMOSUS (BY PHADIA)', None, None),
    ('ALLERGY MUGWORT (BY PHADIA)', None, None),
    ('ALLERGY NUT PANEL (BY PHADIA)', None, None),
    ('ALLERGY NON-VEGETARIAN PANEL 1 (BY PHADIA)', None, None),
    ('ALLERGY NON-VEGETARIAN PANEL 2 (BY PHADIA)', None, None),
    ('ALLERGY OAT (BY PHADIA)', None, None),
    ('ALLERGY ONION (BY PHADIA)', None, None),
    ('ALLERGY ORANGE (BY PHADIA)', None, None),
    ('ALLERGY PAPRIKA- SWEET PEPPER (BY PHADIA)', None, None),
    ('ALLERGY PAPAYA (BY PHADIA)', None, None),
    ('ALLERGY PARROT FEATHERS (BY PHADIA)', None, None),
    ('ALLERGY PEA (BY PHADIA)', None, None),
    ('ALLERGY PENICILLOYL G (BY PHADIA)', None, None),
    ('ALLERGY PEANUT (BY PHADIA)', None, None),
    ('ALLERGY PEAR (BY PHADIA)', None, None),
    ('ALLERGY PENICILLOYL V (BY PHADIA)', None, None),
    ('ALLERGY PHADIATOP PEDIATRIC', None, None),
    ('ALLERGY PHADIATOP ADULT', None, None),
    ('ALLERGY PIGEON FEATHERS (BY PHADIA)', None, None),
    ('ALLERGY PINEAPPLE (BY PHADIA)', None, None),
    ('ALLERGY POLLEN PANEL (BY PHADIA)', None, None),
    ('ALLERGY PORK (BY PHADIA)', None, None),
    ('ALLERGY POTATO (BY PHADIA)', None, None),
    ('ALLERGY RICE (BY PHADIA)', None, None),
    ('ALLERGY RYE GRASS (BY PHADIA)', None, None),
    ('ALLERGY SALMON (BY PHADIA)', None, None),
    ('ALLERGY SESAME SEED (BY PHADIA)', None, None),
    ('ALLERGY SHRIMP (BY PHADIA)', None, None),
    ('ALLERGY SOYBEAN (BY PHADIA)', None, None),
    ('ALLERGY SPINACH (BY PHADIA)', None, None),
    ('ALLERGY STRAWBERRY (BY PHADIA)', None, None),
    ('ALLERGY TIMOTHY GRASS (BY PHADIA)', None, None),
    ('ALLERGY TOMATO (BY PHADIA)', None, None),
    ('ALLERGY TUNA (BY PHADIA)', None, None),
    ('ALLERGY TURKEY MEAT (BY PHADIA)', None, None),
    ('ALLERGY VEGETABLE PANEL 1 (BY PHADIA)', None, None),
    ('ALLERGY VEGETABLE PANEL 2 (BY PHADIA)', None, None),
    ('ALLERGY VEGETABLE PANEL 3 (BY PHADIA)', None, None),
    ('ALLERGY WALNUT (BY PHADIA)', None, None),
    ('ALLERGY WHEAT (BY PHADIA)', None, None),
    ('ALLERGY YEAST (BY PHADIA)', None, None),
    ('ANTI SPERM ANTIBODY (ASAB)', None, None),
    ('ANTI SACCHAROMYCES CEREVISIAE IGA ANTIBODIES', None, None),
    ('ANTI SACCHAROMYCES CEREVISIAE IGG ANTIBODIES', None, None),
    ('ANTI STREPTOLYSIN - O (ASO)', None, None),
    ('ACTIVE VITAMIN B12 (HOLOTRANSCOBALAMIN)', None, None),
    ('BETA 2 GLYCOPROTEIN 1 - IGG', None, None),
    ('BETA 2 GLYCOPROTEIN 1 - IGM', None, None),
    ('BETA2 MICROGLOBULIN', None, None),
    ('BICARBONATE', None, None),
    ('BLOOD KETONE (D3HB)', None, None),
    ('SILVER', None, None),
    ('ALUMINIUM', None, None),
    ('ARSENIC', None, None),
    ('BARIUM', None, None),
    ('BERYLLIUM', None, None),
    ('BISMUTH', None, None),
    ('CADMIUM', None, None),
    ('COBALT', None, None),
    ('CHROMIUM', None, None),
    ('CAESIUM', None, None),
    ('COPPER', None, None),
    ('MERCURY', None, None),
    ('MANGANESE', None, None),
    ('MOLYBDENUM', None, None),
    ('NICKEL', None, None),
    ('LEAD', None, None),
    ('ANTIMONY', None, None),
    ('SELENIUM', None, None),
    ('TIN', None, None),
    ('STRONTIUM', None, None),
    ('THALLIUM', None, None),
    ('URANIUM', None, None),
    ('VANADIUM', None, None),
    ('ZINC', None, None),
    ('BETA-THALASSEMIA SCREENING', None, None),
    ('COMPLEMENT 3 (C3)', None, None),
    ('COMPLEMENT 4 (C4)', None, None),
    ('CA 72.4-GASTRIC CANCER MARKER', None, None),
    ('PR3 - ANCA (C-ANCA)', None, None),
    ('CARBAMAZEPINE / TEGRETOL', None, None),
    ('CD3CD4CD8', None, None),
    ('CERULOPLASMIN', None, None),
    ('CHROMOGRANIN A', None, None),
    ('CHLAMYDIA TRACHOMATIS IGG ANTIBODIES', None, None),
    ('CHOLINESTERASE', None, None),
    ('CVP', None, None),
    ('CYSTATIN C', None, None),
    ('ANTI DEAMIDATED GLIADIN PEPTIDE - IGA', None, None),
    ('ANTI DEAMIDATED GLIADIN PEPTIDE - IGG', None, None),
    ('DIHYDROTESTOSTERONE (DHT)', None, None),
    ('DIGOXIN', None, None),
    ('DOUBLE MARKER FIRST TRIMESTER 8-13 WEEKS', None, None),
    ('E22', None, None),
    ('UNCONJUGATED ESTRIOL (E3)', None, None),
    ('EPSTEIN BARR VIRAL CAPSID ANTIGEN - IGG', None, None),
    ('ECHINOCOCCUS - IGG', None, None),
    ('ERYTHROPOIETIN', None, None),
    ('FATSVP', None, None),
    ('FILARIA ANTIGEN RAPID TEST', None, None),
    ('FOOD INTOLERANCE PROFILE', None, None),
    ('FRUCTOSAMINE', None, None),
    ('GASTRIN', None, None),
    ('ANTI GLOMERULAR BASEMENT MEMBRANE PROTEIN - IGG', None, None),
    ('HAP', None, None),
    ('HLA-B27', None, None),
    ('HEPATITIS B VIRUS (HBV) QUALITATIVE PCR', None, None),
    ('HEPATITIS B VIRUS (HBV) QUANTITATIVE PCR', None, None),
    ('HEPATITIS C VIRUS - IGG', None, None),
    ('HEPATITIS C VIRUS - IGM', None, None),
    ('HEPATITIS C VIRUS (HCV) QUALITATIVE PCR', None, None),
    ('HEPATITIS C VIRUS (HCV) QUANTITATIVE PCR', None, None),
    ('HUMAN EPIDIDYMIS PROTEIN 4', None, None),
    ('HEPATITIS E VIRUS IGG', None, None),
    ('ANTI HEPATITIS E VIRUS (ANTI HEV) - IGM', None, None),
    ('HAPTOGLOBIN', None, None),
    ('HIV-1 RNA QUALITATIVE PCR', None, None),
    ('HIV-1 RNA QUANTITATIVE PCR', None, None),
    ('HLA B27 QUALITATIVE PCR', None, None),
    ('HELICOBACTER PYLORI - IGA', None, None),
    ('HELICOBACTER PYLORI - IGM', None, None),
    ('IONIC CALCIUM', None, None),
    ('IMMUNOGLOBULIN A (IGA)', None, None),
    ('IMMUNOGLOBULIN E (IGE)', None, None),
    ('IMMUNOGLOBULIN G (IGG)', None, None),
    ('IMMUNOGLOBULIN M (IGM)', None, None),
    ('INSULIN LIKE GROWTH FACTOR 1', None, None),
    ('INHIBIN A', None, None),
    ('INSULIN ANTIBODIES', None, None),
    ('INTERLEUKIN-6', None, None),
    ('KALA AZAR ANTIBODY RAPID TEST', None, None),
    ('KAPPA LIGHT CHAIN', None, None),
    ('LACTATE', None, None),
    ('LAMBDA LIGHT CHAIN', None, None),
    ('LITHIUM', None, None),
    ('LIVER KIDNEY MICROSOMES', None, None),
    ('LEPTOSPIRA-IGM', None, None),
    ('MEASLES ANTIBODY - IGG', None, None),
    ('MEASLES ANTIBODY - IGM', None, None),
    ('MUMPS ANTIBODY - IGG', None, None),
    ('MUMPS ANTIBODY - IGM', None, None),
    ('MYOGLOBIN', None, None),
    ('NEWBORN SCREENING - 4', None, None),
    ('NEONATAL HEMOGLOBIN ELECTROPHORESIS', None, None),
    ('PRE ALBUMIN SERUM', None, None),
    ('MPO - ANCA (P - ANCA)', None, None),
    ('PREGNANCY ASSOCIATED PLASMA PROTEIN A', None, None),
    ('PHENOBARBITAL/GARDENAL SERUM', None, None),
    ('PHENYTOIN / DILANTIN / EPTOIN', None, None),
    ('PLACENTAL GROWTH FACTOR', None, None),
    ('PROCALCITONIN', None, None),
    ('PROTEIN ELECTROPHORESIS', None, None),
    ('PROPERDIN FACTOR B', None, None),
    ('PYRUVATE', None, None),
    ('QUADRUPLE MARKER SECOND TRIMESTER 14-22 WEEKS', None, None),
    ('ANA TITRE (IMMUNOFLUORESCENCE)', None, None),
    ('STEROID', None, None),
    ('SERUM AMYLOID A PROTEIN', None, None),
    ('ANTI SCL - 70 ANTIBODY', None, None),
    ('SMALL DENSE LDL', None, None),
    ('SOLUBLE FMS-LIKE TYROSINE KINASE 1', None, None),
    ('SIALIC ACID', None, None),
    ('TACROLIMUS ASSAY', None, None),
    ('TOTAL BILE ACID', None, None),
    ('TRIPLE MARKER SECOND TRIMESTER 14-22 WEEKS', None, None),
    ('TREPONEMA PALLIDUM ANTIBODY (TPAB)', None, None),
    ('TSH RECEPTOR ANTIBODIES', None, None),
    ('TRANSFERRIN', None, None),
    ('TISSUE TRANSGLUTAMINASE (TTG) ANTIBODY IGA (CLIA)', None, None),
    ('UREA', None, None),
    ('VALPROIC ACID', None, None),
    ('VARICELLA ZOSTER VIRUS ANTIBODY - IGG', None, None),
    ('VARICELLA ZOSTER VIRUS ANTIBODY - IGM', None, None),
    ('VITAMIN D 1.25 - DIHYDROXY', None, None),
    ('VDP', None, None),
    ('VITAMIN A', None, None),
    ('VITAMIN B1/THIAMIN', None, None),
    ('VITAMIN B2/RIBOFLAVIN', None, None),
    ('VITAMIN B3/NICOTINIC ACID', None, None),
    ('VITAMIN B5/PANTOTHENIC', None, None),
    ('VITAMIN B6/PYRIDOXAL - 5 - PHOSPHATE', None, None),
    ('VITAMIN B7/BIOTIN', None, None),
    ('VITAMIN B9/FOLIC ACID', None, None),
    ('VITAMIN D3', None, None),
    ('VITAMIN E', None, None),
    ('VITAMIN K', None, None),
    ('WBCVP', None, None),
    ('HIV - WESTERN BLOT', None, None),
    ('ALA - 24 HRS URINE', None, None),
    ('ALA - RANDOM URINE', None, None),
    ('B - 2 MICROGLOBULIN-URINE', None, None),
    ('BIOGENIC AMINES-24 HOURS URINE', None, None),
    ('BK POLIOMA VIRUS (URINE) QUANTITATIVE BY REAL-TIME PCR', None, None),
    ('C/S - AEROBIC - URINE', None, None),
    ('CATECHOLAMINE -24 HOURS URINE', None, None),
    ('CATECHOLAMINE -RANDOM URINE', None, None),
    ('DOPAMINE-24 HOURS URINE', None, None),
    ('FREE KAPPA LAMBDA CHAIN RATIO-URINE', None, None),
    ('HEAVY METAL ANALYSIS FROM URINE', None, None),
    ('HISTOPLASMA CAPSULATUM ANTIGEN FROM URINE', None, None),
    ('HOMOVANILLIC ACID (HVA) - 24-HOUR URINE', None, None),
    ('LEAD LEVEL - 24 HRS URINE', None, None),
    ('LEGIONELLA PNEUMOPHILIA ANTIGEN FROM URINE', None, None),
    ('MICROALBUMIN LEVEL FROM URINE', None, None),
    ('OSMOLALITY URINE', None, None),
    ('PORPHOBILINOGEN - 24 HRS URINE (PBG) QUANTITATIVE', None, None),
    ('PORPHOBILINOGEN - RANDOM URINE (PBG) QUANTITATIVE', None, None),
    ('PORPHYRIA WORK UP - 24 HRS URINE', None, None),
    ('PORPHYRIA WORK UP - RANDOM URINE', None, None),
    ('PORPHYRINS - 24 HRS URINE', None, None),
    ('PORPHYRINS - RANDOM URINE', None, None),
    ('SEROTONIN LEVEL-URINE', None, None),
    ('STD 32 PATHOGEN URINE AND BLOOD', None, None),
    ('STREPTOCOCCUS PNEUMONIAE ANTIGEN FROM URINE', None, None),
    ('URINE ALBUMIN', None, None),
    ('URINE CITRATE - 24 HRS', None, None),
    ('URINE ELECTROPHORESIS', None, None),
    ('URINE EXAMINATION', None, None),
    ('URINE EXAMINATION -U (FLOW CYTOMETRY)', None, None),
    ('URINE FOR HAEMOSIDERIN PIGMENT', None, None),
    ('URINE IMMUNOELECTROPHORESIS', None, None),
    ('URINE METABOLIC SCREEN FOR STONE', None, None),
    ('URINE MYOGLOBIN', None, None),
    ('URINE OXALATE - 24 HRS', None, None),
    ('URINE PORPHOBILINOGEN - QUALITATIVE', None, None),
    ('ZINC-24 HOURS URINE', None, None),
    ('URINE ANALYSIS (ROUTINE)', None, None),
    ('PROTEIN- TOTAL (24 HOUR URINE)', None, None),
    ('PROTEIN- TOTAL (RANDOM URINE)', None, None),
    ('TOTAL PROTEIN / CREATININE RATIO IN URINE', None, None),
    ('MICROALBUMIN - QUANTITATIVE (24 HOUR URINE)', None, None),
    ('MICROALBUMIN - QUANTITATIVE (RANDOM URINE)', None, None),
    ('MICROALBUMIN /CREATININE RATIO - URINE', None, None),
    ('URINE ANALYSIS', None, None),
    ('BILIRUBIN (RANDOM URINE)', None, None),
    ('GLUCOSE - QUALITATIVE (URINE)', None, None),
    ('GLUCOSE (24 HOUR URINE)', None, None),
    ('UREA (24 HOUR URINE)', None, None),
    ('UREA NITROGEN - 24 HOUR URINE', None, None),
    ('URIC ACID (24 HOUR URINE)', None, None),
    ('URIC ACID (RANDOM URINE)', None, None),
    ('CREATININE (24 HOUR URINE)', None, None),
    ('CREATININE (RANDOM URINE)', None, None),
    ('CALCIUM (24 HOUR URINE)', None, None),
    ('COLONY FOR IDENTIFICATION & SENSITIVITY (URINE - SEMEN)', None, None),
    ('URINE DRUG SCREENING: 9 DRUGS (AMPHETAMINE - BARBITURATES - BENZODIAZEPINES - COCAINE - CANNABIS - OPIATES - PHENCYCLIDINE - METHAMPHETAMINE - METHODONE)', None, None),
    ('CULTURE & SENSITIVITY - URINE', None, None),
    ('CULTURE FOR MYCOLASMA & UREAPLASMA - URINE', None, None),
    ('ALDOSTERONE 24 HR URINE', None, None),
    ('AMYLASE - TOTAL (24 HOUR URINE)', None, None),
    ('AMYLASE - TOTAL (RANDOM URINE)', None, None),
    ('B-2 MICROGLOBULIN IN URINE', None, None),
    ('BILE SALTS & PIGMENTS - URINE', None, None),
    ('CALCIUM (RANDOM URINE)', None, None),
    ('FINGAL CULTURE AND IDENTIFICATION URINE', None, None),
    ('KETONES (RANDOM URINE)', None, None),
    ('LEAD - URINE 24 HRS', None, None),
    ('MAGNESIUM (24 HOUR URINE)', None, None),
    ('NICOTINE METABOLITE QUALITATIVE URINE SPOT', None, None),
    ('PHOSPHOROUS (24 HOUR URINE)', None, None),
    ('PHOSPHOROUS (RANDOM URINE)', None, None),
    ('POTASSIUM (K) (24 HOUR URINE)', None, None),
    ('POTASSIUM (K) (RANDOM URINE)', None, None),
    ('REDUCING SUBSTANCES (URINE)', None, None),
    ('SODIUM (NA) (24 HOUR URINE)', None, None),
    ('SODIUM (NA) (RANDOM URINE)', None, None),
    ('UROBILINOGEN (RANDOM URINE)', None, None),
    ('CULTURE AND SENSITIVITY AEROBIC SEMEN', None, None),
    ('GLOMERULO BASEMENT MEMBRANE ANTIBODY', None, None),
    ('SEMEN ANALYSIS - NML', None, None),
    ('SEMEN ANALYSIS - AUTO', None, None),
    ('SEMEN ANALYSIS (ROUTINE)', None, None),
    ('COLONY FOR IDENTIFICATION - SENSITIVITY (URINE SEMEN)', None, None),
    ('SEMEN ANALYSIS', None, None),
    ('CULTURE AND SENSITIVITY - SEMEN', None, None),
    ('CULTURE AND SENSITIVITY (MYCOLASMA / UREA PLASMA) - SEMEN', None, None),
    ('CULTURE AND SENSITIVITY (SEMEN)', None, None),
    ('ECG RESTING', None, None),
    ('2D ECHO', None, None),
    ('TREADMILL', None, None),
    ('DENT X-RAY HEAD FOR ORTHODONTIA', None, None),
    ('DENT ORTHOPANTOGRAM', None, None),
    ('DENT CBCT (SINGLE) MAXILLA OR MANDIBLE', None, None),
    ('DENT CBCT FULL DENTAL ARC', None, None),
    ('DENT CBCT LIMITED FIELD OF VIEW', None, None),
    ('CAROTID DOPPLER EXTRACRANIAL ARTERIES COMPLETE BILATERAL STUDY', None, None),
    ('CERVICAL SPINE EXTRA LEVEL', None, None),
    ('PERIPHERAL DOPPLER STUDY', None, None),
    ('SOFT TISSUE DOPPLER STUDY', None, None),
    ('THORACIC SPINE EXTRA LEVEL', None, None),
    ('MRI UPPER EXTREMITIES OTHER THAN JOINT WITHOUT CONTRAST', None, None),
    ('MRI UPPER EXTREMITIES OTHER THAN JOINT WITH CONTRAST', None, None),
    ('MRI LOWER EXTREMITIES OTHER THAN JOINT WITH CONTRAST MATERIAL', None, None),
    ('MRI HEAD/BRAIN/PITUITARY (INCLUDING BRAIN STEM) WITH CONTRAST', None, None),
    ('MRI HEAD/BRAIN/PITUITARY(INCLUDING BRAIN STEM) WITHOUT CONTRAST', None, None),
    ('MRI ANGIOGRAPHY', None, None),
    ('MRI AORTA AND BRANCHES/MR UROGRAM', None, None),
    ('MRI BREAST WITHOUT AND OR WITH CONTRAST MATERIAL BILATERAL', None, None),
    ('MRI BREAST WITHOUT AND OR WITH CONTRAST MATERIAL UNLATERAL', None, None),
    ('MRI CERVICAL SPINE WITH CONTRAST', None, None),
    ('MRI CERVICAL SPINE WITHOUT CONTRAST', None, None),
    ('MRI CHEST WITH CONTRAST', None, None),
    ('MRI CHEST WITHOUT CONTRAST', None, None),
    ('MRI DORSO LUMBAR SPINE', None, None),
    ('MRI FULL ABDOMEN', None, None),
    ('MRI KNEE/ANKLE JOINT WITHOUT CONTRAST', None, None),
    ('MRI KNEE/ANKLE JOINT WITH CONTRAST', None, None),
    ('MRI LOWER EXTREMITIES OTHER THAN JOINT WITHOUT CONTRAST MATERIAL', None, None),
    ('MRI LUMBER SPINE WITH CONTRAST', None, None),
    ('MRI LUMBER SPINE WITHOUT CONTRAST', None, None),
    ('MRI SHOULDER JOINT WITHOUT CONTRAST MATERIALS', None, None),
    ('MRI SHOULDER JOINT WITH CONTRAST MATERIALS', None, None),
    ('MRI SOFT TISSUE (ORBIT FACE AND OR NECK) WITHOUT CONTRAST MATERIAL', None, None),
    ('MRI SOFT TISSUE (ORBIT FACE AND OR NECK) WITH CONTRAST MATERIAL', None, None),
    ('MRI THORACIC SPINE', None, None),
    ('MRI TMJ', None, None),
    ('MRI-ABDOMEN WITH CONTRAST', None, None),
    ('MRI-PELVIS WITH CONTRAST MATERIALS', None, None),
    ('MRI-PELVIS WITHOUT CONTRAST MATERIALS', None, None),
    ('C.T. SCAN MYELOGRAPHY/CISTERBOGRAPHY)', None, None),
    ('CT SCAN LOWER EXTREMETIES WITH CONTRAST', None, None),
    ('CT SCAN LOWER EXTREMETIES WITHOUT CONTRAST', None, None),
    ('CT SCAN LUMBAR SPINE WITH CONTRAST', None, None),
    ('CT SCAN LUMBAR SPINE WITHOUT CONTRAST', None, None),
    ('CT SCAN MEDIASTINUM/CHEST/ THORAX WITH CONTRAST', None, None),
    ('CT SCAN MEDIASTINUM/CHEST/THORAX WITHOUT CONTRAST', None, None),
    ('CT SCAN THORACIC SPINE WITHOUT CONTRAST', None, None),
    ('CT SCAN UPPER ABDOMEN WITH CONTRAST', None, None),
    ('CT SCAN UPPER ABDOMEN WITHOUT CONTRAST', None, None),
    ('CT SCAN WHOLE ABDOMEN (PLAIN) (ABDOMEN AND PELIVS WITHOUT CONTRAST)', None, None),
    ('CT SCAN CERVICAL SPINE WITH CONTRAST MATERIALS', None, None),
    ('CT SCAN CERVICAL SPINE WITHOUT CONTRAST MATERIALS', None, None),
    ('CT SCAN LOWER ABDOMEN/PELVIS WITH OUT CONTRAST', None, None),
    ('CT SCAN OSTEO CT (BONE MINERAL DENSITY ASSES) ONE OR MORE SITES APPENDICULAR SKELETON', None, None),
    ('CT SCAN SINUSES ROUTINE WITH CONTRAST', None, None),
    ('CT SCAN SINUSES ROUTINE WITHOUT CONTRAST', None, None),
    ('CT SCAN SOFT TISSUE NECK WITH CONTRAST', None, None),
    ('CT SCAN SOFT TISSUE NECK WITHOUT CONTRAST', None, None),
    ('CT SCAN T.M.JOINT WITHOUT CONTRAST', None, None),
    ('CT MASTIOD (CT ORBIT SELLA OR POSTERIOR FOSSA OR OUTER MIDDLE OR INNER EAR) WITH CONTRAST MATERIAL', None, None),
    ('CT MASTIOD (CT ORBIT SELLA OR POSTERIOR FOSSA OR OUTER MIDDLE OR INNER EAR) WITHOUT CONTRAST MATERIAL', None, None),
    ('CT ANGIOGRAPHY', None, None),
    ('CT SCAN ABDOMEN WITH CONTRAST', None, None),
    ('CT SCAN BRAIN OR HEAD/SELLA TURCICA WITH CONTRAST', None, None),
    ('CT SCAN BRAIN/SELLA TURCICA', None, None),
    ('CT SCAN HIP JOINT (PELVIC) WITH CONTRAST', None, None),
    ('CT SCAN LOWER ABDOMEN WITH CONTRAST', None, None),
    ('CT SCAN UPPER EXTREMITY WITH CONTRAST', None, None),
    ('CT SCAN UPPER EXTREMITY WITHOUT CONTRAST', None, None),
    ('CT-DORSAL/THORACIC SPINE WITH CONTRAST', None, None),
    ('LUMBAR SPINE EXTRA LEVEL', None, None),
    ('CONE BEAM COMPUTER TOMOGRAPHY', None, None),
    ('ULTRASOUND PREG (TWINS) EACH ADDITIONAL GESTATION', None, None),
    ('ULTRASOUND DOPPLER STUDY BOTH LIMB (EXTREMITY VEINS INCLUDING RESPONSES TO COMPRESSION AND OTHER MANEUVERS COMPLETE BILATERAL STUDY)', None, None),
    ('ULTRASOUND DOPPLER STUDY SINGLE LIMB (UNILATERAL OR LIMITED STUDY)', None, None),
    ('ULTRASOUND DOPPLER ABDOMEN', None, None),
    ('ULTRASOUND FULL ABDOMEN', None, None),
    ('ULTRASOUND SCREEING ONLY', None, None),
    ('ULTRASOUND - PREGNANT UTERUS - REAL TIME WITH IMAGE DOCUMENTATION - FOLLOW-UP (EG RE-EVALUATION OF FETAL SIZE BY MEASURING STANDARD GROWTH PARAMETERS AND AMNIOTIC FLUID VOLUME - RE-EVALUATION OF ORGAN SYSTEM(S) SUSPECTED OR CONFIRMED TO BE ABNORMAL ON A PREVIOUS SCAN) - TRANSABDOMINAL APPROACH - PER FETUS', None, None),
    ('ULTRASOUND - PREGNANT UTERUS - REAL TIME WITH IMAGE DOCUMENTATION - LIMITED (EG - FETAL HEART BEAT - PLACENTAL LOCATION - FETAL POSITION AND/OR QUALITATIVE AMNIOTIC FLUID VOLUME) - 1 OR MORE FETUSES', None, None),
    ('USG BREAST (UNILATERAL OR BILATERAL) REAL TIME WITH IMAGE DOCUMENTATION', None, None),
    ('USG ANOMALY SCAN', None, None),
    ('USG EXTREMITIES', None, None),
    ('USG HEAD', None, None),
    ('USG KUB PROSTATE', None, None),
    ('USG LOWER ABDOMEN /PELVIC/KUB REAL TIME WITH IMAGE DOCUMENTATION COMPLETE (NON OBSTETRIC)', None, None),
    ('USG PREGNANCY DOPPLER', None, None),
    ('USG PREGNANCY REAL TIME WITH IMAGE DOCUMENTATION FETAL AND METERNAL EVALUATION FIRST TRIMESTER TRANS ABDOMINAL APPROACH SINGLE OR FIRST GESTATION', None, None),
    ('USG PREGNANT UTERUS REAL TIME WITH IMAGE DOCUMENTATION TRANSVAGINAL', None, None),
    ('USG PROSTATE VOLUME STUDY FOR BRACHYTHERAPY TREATMENT PLANNING', None, None),
    ('USG RENAL DOPPLER', None, None),
    ('USG SCROTUM', None, None),
    ('USG SOFT TISSUE OF HEAD AND NECK/THYROID REAL TIME WITH IMAGE', None, None),
    ('USG TRANSRECTIAL', None, None),
    ('USG UPPER ABDOMEN REAL TIME WITH IMAGE DOCUMENTATION', None, None),
    ('USG VAGINAL', None, None),
    ('ULTRASOUND FOLLICULAR SCAN (LIMITED OR FOLLOW UP)', None, None),
    ('X-RAY MASTOID COMPLETE MINIMUM OF 3 VIEWS', None, None),
    ('X-RAY ABDOMAN OR KUB/GB', None, None),
    ('X-RAY ADENOID/NECK', None, None),
    ('X-RAY ANKLE JOINT (TWO VIEWS)', None, None),
    ('X-RAY BARIUM ENEMA', None, None),
    ('X-RAY BARIUM MEAL', None, None),
    ('X-RAY BARIUM MEALAND FOLLOW THROUGH TO IC REGION', None, None),
    ('X-RAY BARIUM SWALLOW', None, None),
    ('X-RAY CALCANEUM/HEEL (TWO VIEWS)', None, None),
    ('X-RAY CEPHALOMETRY', None, None),
    ('X-RAY CERVICAL SPINE - 4 VIEWS', None, None),
    ('X-RAY CERVICAL SPINE 2 OR 3 VIEWS', None, None),
    ('X-RAY CHEST AP AND LATERAL', None, None),
    ('X-RAY CHEST RIBS (ONE VIEW)', None, None),
    ('X-RAY CHEST SINGLE VIEW FRONTAL', None, None),
    ('X-RAY CLAVICLE COMPLETE', None, None),
    ('X-RAY ELBOW JOINT (AP LAT)', None, None),
    ('X-RAY FACIAL BONES - 3 VIEWS', None, None),
    ('X-RAY FACIAL BONES/SKULL LESS THAN 3 VIEWS', None, None),
    ('X-RAY FEMUR (AP LAT)', None, None),
    ('X-RAY FOOT (TWO VIEWS)', None, None),
    ('X-RAY FOR BONE AGE', None, None),
    ('X-RAY FOREARM (AP LAT)', None, None),
    ('X-RAY HAND (AP LAT)', None, None),
    ('X-RAY HIP JOINT', None, None),
    ('X-RAY HIP JOINT (TWO VIEWS)', None, None),
    ('X-RAY HUMERUS (AP LAT)', None, None),
    ('X-RAY HYSTEROSALPINGOGRAPHY(HSG)', None, None),
    ('X-RAY INTRAVENOUS PYELOGRAPHY (IVP)', None, None),
    ('X-RAY INTRENAL AUDIOTORY MEATI COMPLETE', None, None),
    ('X-RAY KNEE JOINT 1 OR 2 VIEWS', None, None),
    ('X-RAY L S SPINE -2 OR 3 VIEWS', None, None),
    ('X-RAY LEG TIBIA AND FIBULA', None, None),
    ('X-RAY MANDIBLE OBLIQUE TWO VIEWS', None, None),
    ('X-RAY MANDIBLE PARTIAL LESS THAN 4 VIEWS', None, None),
    ('X-RAY MASTOID LES THAN 3 VIEW PER SIDE', None, None),
    ('X-RAY MICTURING CYSTOGRAPHY', None, None),
    ('X-RAY NASAL BONES (EACH VIEW)', None, None),
    ('X-RAY NASOPHARYNX (EACH VIEW)', None, None),
    ('X-RAY OPTIC FORAMINA (RHESE GOALWIN VIEW)', None, None),
    ('X-RAY PANORAMIC VIEW', None, None),
    ('X-RAY PARANASAL SINUSES LESS THAN 3 VIEWS', None, None),
    ('X-RAY PATELLA (LAT AND AXIAL)', None, None),
    ('X-RAY PELVIS (EACH VIEW)', None, None),
    ('X-RAY RETROGRADE CYSTOGRAPHY/URETHOROGRAPHY', None, None),
    ('X-RAY RIBS', None, None),
    ('X-RAY SACRO-ILIAC JOINT LESS THAN 3 VIEWS', None, None),
    ('X-RAY SACRUM AND COCCYX', None, None),
    ('X-RAY SCAPULA COMPLETE', None, None),
    ('X-RAY SHOULDER JOINT TWO VIEWS', None, None),
    ('X-RAY SHOULDER JOINT(ONE VIEW)', None, None),
    ('X-RAY SINOGRAM', None, None),
    ('X-RAY SKULL LESS THAN 4 VIEWS', None, None),
    ('X-RAY SKULL PETROUS BONE STENVERS', None, None),
    ('X-RAY SKULL SELLA TURCICA', None, None),
    ('X-RAY SPINE (EACH VIEW)', None, None),
    ('X-RAY STERNOCLAVICULAR JOINT (EACH VIEW)', None, None),
    ('X-RAY STERNUM', None, None),
    ('X-RAY T.M. JOINT', None, None),
    ('X-RAY THORACIC SPINE - 2 VIEWS', None, None),
    ('X-RAY THORACO LUMBAR SPINE STANDING', None, None),
    ('X-RAY THUMB AND FINGER (AP LAT)', None, None),
    ('X-RAY TOES(TWO VIEWS)', None, None),
    ('X-RAY VENOGRAM/ARTHROGRAPHY/FISTULOGRAPHY', None, None),
    ('X-RAY WRIST JOINT (AP LAT)', None, None),
    ('X-RAY T.M. JOINTS TOMOGRAPHY', None, None),
    ('X-RAY ABDOMEN SUPINE/ERECT/KUB', None, None),
    ('X-RAY ANKLE JOINT AP/LATERAL VIEW', None, None),
    ('X-RAY BOTH KNEES', None, None),
    ('X-RAY APICAL LORDOTIC VIEW', None, None),
    ('X-RAY CALCANEUM TWO VIEWS', None, None),
    ('X-RAY CERVICAL SPINE ONE VIEW/L-S SPINE ONE VIEW', None, None),
    ('X-RAY CERVICAL SPINE TWO VIEWS', None, None),
    ('X-RAY CHEST EACH VIEW', None, None),
    ('X-RAY CHEST PA/LATERAL VIEW', None, None),
    ('X-RAY CHEST RIBS EACH VIEW', None, None),
    ('X-RAY CLAVICLE EACH SIDE', None, None),
    ('X-RAY ELBOW JOINT AP/LATERAL VIEW', None, None),
    ('X-RAY FACIAL BONES EACH VIEW', None, None),
    ('X-RAY FEMUR EACH VIEW AP/LATERAL', None, None),
    ('X-RAY FINGERS', None, None),
    ('X-RAY FOOT TWO VIEWS', None, None),
    ('X-RAY FOREARM AP/LATERAL VIEW', None, None),
    ('X-RAY HAND AP/OBLIQUE VIEW', None, None),
    ('X-RAY HIP JOINT AP/OBLIQUE TWO VIEWS', None, None),
    ('X-RAY HIP JOINT FROG POSITION', None, None),
    ('X-RAY HUMERUS AP/LATERAL VIEW', None, None),
    ('X-RAY INTERNAL AUDITORY CANAL EACH SIDE', None, None),
    ('X-RAY KNEE JOINT AP/LATERAL VIEW', None, None),
    ('X-RAY KNEE JOINT THREE VIEW', None, None),
    ('X-RAY LOWER LEG AP/LATERAL 2 VIEWS', None, None),
    ('X-RAY LUMBAR SPINE 2VIEWS', None, None),
    ('X-RAY LUMBO-SACRAL SPINE EACH VIEW', None, None),
    ('X-RAY LUMBO-SACRAL SPINE 4 VIEWS AP/L/OBLS', None, None),
    ('X-RAY MANDIBLE EACH VIEW', None, None),
    ('X-RAY MASTOIDS 1 VIEW', None, None),
    ('X-RAY NASAL BONES EACH VIEW', None, None),
    ('X-RAY NASO PHARYNX (ADENOIDS)', None, None),
    ('X-RAY OPTIC FORAMEN EACH SIDE', None, None),
    ('X-RAY PARANASAL SINUSES 2 VIEW (WATERS AND CALDWELL VIEW)', None, None),
    ('X-RAY PATELLA', None, None),
    ('X-RAY PELVIS EACH VIEW', None, None),
    ('X-RAY SACRO-ILIAC EACH VIEW', None, None),
    ('X-RAY SACRUM/COCCYX 2 VIEW', None, None),
    ('X-RAY SCAPULA EACH VIEW', None, None),
    ('X-RAY SHOULDER JOINT 2 VIEWS AP/AXIAL VIEW', None, None),
    ('X-RAY SKULL AP/LATERAL 2 VIEWS', None, None),
    ('X-RAY SKULL PETROUS BONE(SCHULLERS VIEW)', None, None),
    ('X-RAY SKULL PETROUS BONE(STENVERS VIEW)', None, None),
    ('X-RAY SKULL TOWNES VIEW', None, None),
    ('X-RAY SKULL ZYGOMATIC ARCH EACH SIDE', None, None),
    ('X-RAY STERNUM EACH VIEW/STERNO-CLAVICULAR JOINT', None, None),
    ('X-RAY THORACIC SPINE 2 VIEWS', None, None),
    ('X-RAY THORACIC SPINE EACH VIEW', None, None),
    ('X-RAY TM JOINTS 2 VIEWS EACH SIDE', None, None),
    ('X-RAY WRIST JOINT AP/LATERAL VIEW', None, None),
    ('USG ABDOMINO-PELVIC SCAN (WHOLE ABDOMEN)', None, None),
    ('USG BREAST SCAN', None, None),
    ('USG FOLLICULAR SCAN', None, None),
    ('USG HEPATOBILLIARY SCAN', None, None),
    ('USG PELVIC SCAN/PROSTATE SCAN', None, None),
    ('USG LOWER ABDOMINAL SCAN', None, None),
    ('USG PREGNANCY SCAN - 14 WEEKS AND MORE', None, None),
    ('USG PREGNANCY SCAN - FETAL BIO PHYSICAL PROFILE', None, None),
    ('USG PREGNANCY SCAN EARLY', None, None),
    ('USG PREGNANCY SCAN -NT', None, None),
    ('USG PREGNANCY SCAN - ANOMOLY', None, None),
    ('USG RENAL SCAN', None, None),
    ('USG SCROTAL SCAN', None, None),
    ('USG SOFT TISSUE SCAN', None, None),
    ('USG THYROID SCAN', None, None),
    ('USG TRANS RECTAL SCAN', None, None),
    ('USG TRANS VAGINAL SCAN', None, None),
    ('USG TRANSVAGINAL PREGNANCY SCAN', None, None),
    ('USG UPPER/LOWER ABDONIMAL SCAN/HEPAT0-BILIARY SCAN', None, None),
    ('USG URINARY TRACT SCAN', None, None),
    ('FOOD ALLERGY - 60 PANEL', None, None),
    ('RAST FOOD PANEL 44 PARAMETERS', None, None),
    ('FOOD INHALENT TEST - 60 PANEL', None, None),
    ('FOOD INTOLERANCE TEST', None, None),
]


def seed_admin(db) -> None:
    existing = db.query(Admin).filter(Admin.username == settings.ADMIN_USERNAME).first()
    if existing:
        print(f"Admin '{settings.ADMIN_USERNAME}' already exists - skipped.")
        return

    admin = Admin(
        username=settings.ADMIN_USERNAME,
        email=settings.ADMIN_EMAIL,
        password_hash=hash_password(settings.ADMIN_PASSWORD),
    )
    db.add(admin)
    print(f"Created admin account '{settings.ADMIN_USERNAME}'.")


def seed_parameters(db) -> None:
    created = 0
    for row in PARAMETERS_DATA:
        data = dict(zip(PARAMETER_FIELDS, row))
        existing = db.query(Parameter).filter(Parameter.name == data["name"]).first()
        if existing:
            continue
        db.add(Parameter(**data))
        created += 1
    print(f"Created {created} parameter(s) ({len(PARAMETERS_DATA) - created} already existed).")


def run_seed() -> None:
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        seed_admin(db)
        seed_parameters(db)
        db.commit()
        print("Seed complete.")
    finally:
        db.close()


if __name__ == "__main__":
    run_seed()
