"""add test_code, b2b_price, mrp, parameters_count, tube columns to tests and packages

Revision ID: 2b876f73ff40
Revises: 87672486bffb
Create Date: 2026-08-03 21:20:29.437471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b876f73ff40'
down_revision: Union[str, Sequence[str], None] = '87672486bffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('test_code', sa.String(length=50), nullable=True))
    op.add_column('packages', sa.Column('b2b_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('packages', sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('packages', sa.Column('parameters_count', sa.Integer(), nullable=True))
    op.add_column('packages', sa.Column('tube1', sa.String(length=50), nullable=True))
    op.add_column('packages', sa.Column('tube2', sa.String(length=50), nullable=True))
    op.add_column('packages', sa.Column('tube3', sa.String(length=50), nullable=True))
    op.add_column('packages', sa.Column('tube4', sa.String(length=50), nullable=True))
    op.add_column('packages', sa.Column('included_items', sa.Text(), nullable=True))
    op.create_index(op.f('ix_packages_test_code'), 'packages', ['test_code'], unique=False)
    op.add_column('tests', sa.Column('test_code', sa.String(length=50), nullable=True))
    op.add_column('tests', sa.Column('b2b_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tests', sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tests', sa.Column('parameters_count', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('tube1', sa.String(length=50), nullable=True))
    op.add_column('tests', sa.Column('tube2', sa.String(length=50), nullable=True))
    op.add_column('tests', sa.Column('tube3', sa.String(length=50), nullable=True))
    op.add_column('tests', sa.Column('tube4', sa.String(length=50), nullable=True))
    op.add_column('tests', sa.Column('included_items', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tests_test_code'), 'tests', ['test_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_test_code'), table_name='tests')
    op.drop_column('tests', 'included_items')
    op.drop_column('tests', 'tube4')
    op.drop_column('tests', 'tube3')
    op.drop_column('tests', 'tube2')
    op.drop_column('tests', 'tube1')
    op.drop_column('tests', 'parameters_count')
    op.drop_column('tests', 'mrp')
    op.drop_column('tests', 'b2b_price')
    op.drop_column('tests', 'test_code')
    op.drop_index(op.f('ix_packages_test_code'), table_name='packages')
    op.drop_column('packages', 'included_items')
    op.drop_column('packages', 'tube4')
    op.drop_column('packages', 'tube3')
    op.drop_column('packages', 'tube2')
    op.drop_column('packages', 'tube1')
    op.drop_column('packages', 'parameters_count')
    op.drop_column('packages', 'mrp')
    op.drop_column('packages', 'b2b_price')
    op.drop_column('packages', 'test_code')
    # ### end Alembic commands ###
