"""initial schema

Revision ID: 4249e7c6048f
Revises: 
Create Date: 2026-07-28 23:31:07.296808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4249e7c6048f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('visit_mode', sa.String(length=10), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('lab_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('home_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_lab_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_home_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tat', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_category'), 'packages', ['category'], unique=False)
    op.create_index(op.f('ix_packages_name'), 'packages', ['name'], unique=False)
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow', sa.String(length=200), nullable=False),
    sa.Column('hero_title', sa.String(length=300), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=False),
    sa.Column('hero_stats', sa.JSON(), nullable=False),
    sa.Column('trust_badges', sa.JSON(), nullable=False),
    sa.Column('why_title', sa.String(length=200), nullable=False),
    sa.Column('why_desc', sa.Text(), nullable=False),
    sa.Column('why_cards', sa.JSON(), nullable=False),
    sa.Column('cta_title', sa.String(length=200), nullable=False),
    sa.Column('cta_subtitle', sa.Text(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('site_tagline', sa.String(length=150), nullable=False),
    sa.Column('footer_text', sa.String(length=300), nullable=False),
    sa.Column('pkg_section_title', sa.String(length=200), nullable=False),
    sa.Column('pkg_section_desc', sa.Text(), nullable=False),
    sa.Column('steps_title', sa.String(length=200), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('testi_title', sa.String(length=200), nullable=False),
    sa.Column('testimonials', sa.JSON(), nullable=False),
    sa.Column('certifications_title', sa.String(length=200), nullable=False),
    sa.Column('lab_certifications', sa.JSON(), nullable=False),
    sa.Column('faq_title', sa.String(length=200), nullable=False),
    sa.Column('faq_items', sa.JSON(), nullable=False),
    sa.Column('social_facebook', sa.String(length=300), nullable=True),
    sa.Column('social_instagram', sa.String(length=300), nullable=True),
    sa.Column('social_twitter', sa.String(length=300), nullable=True),
    sa.Column('social_linkedin', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('lab_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('home_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_lab_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_home_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tat', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_category'), 'tests', ['category'], unique=False)
    op.create_index(op.f('ix_tests_name'), 'tests', ['name'], unique=False)
    op.create_table('booking_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_tests',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'test_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_tests')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_tests_name'), table_name='tests')
    op.drop_index(op.f('ix_tests_category'), table_name='tests')
    op.drop_table('tests')
    op.drop_table('site_content')
    op.drop_index(op.f('ix_packages_name'), table_name='packages')
    op.drop_index(op.f('ix_packages_category'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('banners')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
