"""add soft delete status column

Revision ID: 734f492554df
Revises: d32d1074c99e
Create Date: 2026-07-30 00:32:33.076879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734f492554df'
down_revision: Union[str, Sequence[str], None] = 'd32d1074c99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('status', sa.Integer(), nullable=False, server_default='1', comment='1: Active, 2: Inactive, -1: Deleted'))
    op.add_column('banners', sa.Column('status', sa.Integer(), nullable=False, server_default='1', comment='1: Active, 2: Inactive, -1: Deleted'))
    op.add_column('booking_items', sa.Column('status', sa.Integer(), nullable=False, server_default='1', comment='1: Active, 2: Inactive, -1: Deleted'))
    op.add_column('packages', sa.Column('status', sa.Integer(), nullable=False, server_default='1', comment='1: Active, 2: Inactive, -1: Deleted'))
    op.add_column('site_content', sa.Column('status', sa.Integer(), nullable=False, server_default='1', comment='1: Active, 2: Inactive, -1: Deleted'))
    op.add_column('tests', sa.Column('status', sa.Integer(), nullable=False, server_default='1', comment='1: Active, 2: Inactive, -1: Deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'status')
    op.drop_column('site_content', 'status')
    op.drop_column('packages', 'status')
    op.drop_column('booking_items', 'status')
    op.drop_column('banners', 'status')
    op.drop_column('admins', 'status')
    # ### end Alembic commands ###
