"""add parameters, test_parameters, and remaining spec columns

Revision ID: 87672486bffb
Revises: 734f492554df
Create Date: 2026-08-02 23:40:06.740945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87672486bffb'
down_revision: Union[str, Sequence[str], None] = '734f492554df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False, comment='1: Active, 2: Inactive, -1: Deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameters_name'), 'parameters', ['name'], unique=True)
    op.create_table('test_parameters',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'parameter_id')
    )
    op.add_column('bookings', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('packages', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('sample_type', sa.String(length=100), nullable=True))
    op.add_column('tests', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('tests', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'display_order')
    op.drop_column('tests', 'image_url')
    op.drop_column('tests', 'sample_type')
    op.drop_column('packages', 'display_order')
    op.drop_column('bookings', 'address')
    op.drop_table('test_parameters')
    op.drop_index(op.f('ix_parameters_name'), table_name='parameters')
    op.drop_table('parameters')
    # ### end Alembic commands ###
